
#ifndef __SWATCH_LOGGER_LOG4CPLUSCFG__
#define __SWATCH_LOGGER_LOG4CPLUSCFG__

#ifdef __GXX_EXPERIMENTAL_CXX0X__
#define __SWATCH_GXX_EXPERIMENTAL_CXX0X__ __GXX_EXPERIMENTAL_CXX0X__
#undef __GXX_EXPERIMENTAL_CXX0X__
#endif

#include <log4cplus/configurator.h>

#ifdef __SWATCH_GXX_EXPERIMENTAL_CXX0X__
#define __GXX_EXPERIMENTAL_CXX0X__ __SWATCH_GXX_EXPERIMENTAL_CXX0X__
#endif

#endif /* __SWATCH_LOGGER_LOG4CPLUSCFG__ */